
#ifndef COLECCION_DE_EJERCICIOS_EXCEPCIONES_MISFUNCIONES_H
#define COLECCION_DE_EJERCICIOS_EXCEPCIONES_MISFUNCIONES_H


class misfunciones {

};
bool esNegativo(int numero);

#endif //COLECCION_DE_EJERCICIOS_EXCEPCIONES_MISFUNCIONES_H
